import { WeatherThemeType } from '../types/weather';

export interface WMOInfo {
  condition: string;
  description: string;
  themeTypeDay: WeatherThemeType;
  themeTypeNight: WeatherThemeType;
  iconName: string;
  accentColor: string;
  bgGradientDay: string;
  bgGradientNight: string;
}

export const WMO_CODE_MAP: Record<number, WMOInfo> = {
  0: {
    condition: 'Clear Sky',
    description: 'Cloudless, radiant sky with full visibility',
    themeTypeDay: 'clear-day',
    themeTypeNight: 'clear-night',
    iconName: 'Sun',
    accentColor: '#38bdf8',
    bgGradientDay: 'from-sky-500 via-amber-200/20 to-blue-900/40',
    bgGradientNight: 'from-indigo-950 via-slate-900 to-black',
  },
  1: {
    condition: 'Mainly Clear',
    description: 'Scattered high-altitude wisps with abundant sunshine',
    themeTypeDay: 'clear-day',
    themeTypeNight: 'clear-night',
    iconName: 'SunMedium',
    accentColor: '#38bdf8',
    bgGradientDay: 'from-sky-600/90 via-sky-400/20 to-slate-950',
    bgGradientNight: 'from-slate-950 via-indigo-950 to-black',
  },
  2: {
    condition: 'Partly Cloudy',
    description: 'Sunlight filtering through layered cumulus clouds',
    themeTypeDay: 'partly-cloudy-day',
    themeTypeNight: 'partly-cloudy-night',
    iconName: 'CloudSun',
    accentColor: '#60a5fa',
    bgGradientDay: 'from-blue-600/80 via-indigo-400/20 to-slate-950',
    bgGradientNight: 'from-slate-900 via-blue-950/60 to-black',
  },
  3: {
    condition: 'Overcast',
    description: 'Uniform dense cloud deck covering the entire sky',
    themeTypeDay: 'overcast',
    themeTypeNight: 'overcast',
    iconName: 'Cloud',
    accentColor: '#94a3b8',
    bgGradientDay: 'from-slate-700/80 via-slate-800/40 to-slate-950',
    bgGradientNight: 'from-slate-950 via-zinc-900 to-black',
  },
  45: {
    condition: 'Fog',
    description: 'Dense ground-level condensation with restricted visibility',
    themeTypeDay: 'fog',
    themeTypeNight: 'fog',
    iconName: 'CloudFog',
    accentColor: '#cbd5e1',
    bgGradientDay: 'from-slate-600/80 via-zinc-600/30 to-slate-950',
    bgGradientNight: 'from-zinc-950 via-slate-900 to-black',
  },
  48: {
    condition: 'Depositing Rime Fog',
    description: 'Freezing fog forming delicate ice crystals on surfaces',
    themeTypeDay: 'fog',
    themeTypeNight: 'fog',
    iconName: 'CloudFog',
    accentColor: '#a5f3fc',
    bgGradientDay: 'from-teal-900/60 via-slate-800/50 to-slate-950',
    bgGradientNight: 'from-slate-950 via-teal-950/40 to-black',
  },
  51: {
    condition: 'Light Drizzle',
    description: 'Fine, gentle mist-like droplets drifting in the breeze',
    themeTypeDay: 'drizzle',
    themeTypeNight: 'drizzle',
    iconName: 'CloudDrizzle',
    accentColor: '#38bdf8',
    bgGradientDay: 'from-cyan-900/70 via-slate-800/60 to-slate-950',
    bgGradientNight: 'from-slate-950 via-cyan-950/30 to-black',
  },
  53: {
    condition: 'Moderate Drizzle',
    description: 'Continuous damp drizzle dampening outdoor surfaces',
    themeTypeDay: 'drizzle',
    themeTypeNight: 'drizzle',
    iconName: 'CloudDrizzle',
    accentColor: '#0284c7',
    bgGradientDay: 'from-sky-900/80 via-slate-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-sky-950/40 to-black',
  },
  55: {
    condition: 'Dense Drizzle',
    description: 'Heavy clinging mist significantly reducing clarity',
    themeTypeDay: 'drizzle',
    themeTypeNight: 'drizzle',
    iconName: 'CloudDrizzle',
    accentColor: '#0ea5e9',
    bgGradientDay: 'from-sky-950/90 via-slate-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-sky-950 to-black',
  },
  56: {
    condition: 'Light Freezing Drizzle',
    description: 'Sub-zero fine drizzle creating slippery glaze',
    themeTypeDay: 'drizzle',
    themeTypeNight: 'drizzle',
    iconName: 'CloudSnow',
    accentColor: '#7dd3fc',
    bgGradientDay: 'from-cyan-950 via-slate-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-cyan-950 to-black',
  },
  57: {
    condition: 'Dense Freezing Drizzle',
    description: 'Heavy freezing drizzle causing rapid icing on roads',
    themeTypeDay: 'drizzle',
    themeTypeNight: 'drizzle',
    iconName: 'CloudSnow',
    accentColor: '#bae6fd',
    bgGradientDay: 'from-sky-950 via-indigo-950 to-slate-950',
    bgGradientNight: 'from-black via-slate-950 to-black',
  },
  61: {
    condition: 'Slight Rain',
    description: 'Gentle steady rain showers creating fresh atmosphere',
    themeTypeDay: 'rain',
    themeTypeNight: 'rain',
    iconName: 'CloudRain',
    accentColor: '#38bdf8',
    bgGradientDay: 'from-blue-900/80 via-slate-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-blue-950/40 to-black',
  },
  63: {
    condition: 'Moderate Rain',
    description: 'Rhythmic rainfall with cooling winds and puddle runoff',
    themeTypeDay: 'rain',
    themeTypeNight: 'rain',
    iconName: 'CloudRain',
    accentColor: '#2563eb',
    bgGradientDay: 'from-blue-950 via-slate-900/90 to-slate-950',
    bgGradientNight: 'from-slate-950 via-blue-950 to-black',
  },
  65: {
    condition: 'Heavy Rain',
    description: 'Intense torrential downpours with heavy cloud cover',
    themeTypeDay: 'heavy-rain',
    themeTypeNight: 'heavy-rain',
    iconName: 'CloudRain',
    accentColor: '#1d4ed8',
    bgGradientDay: 'from-indigo-950 via-slate-950 to-black',
    bgGradientNight: 'from-black via-indigo-950/40 to-black',
  },
  66: {
    condition: 'Light Freezing Rain',
    description: 'Supercooled liquid droplets freezing on cold contact',
    themeTypeDay: 'rain',
    themeTypeNight: 'rain',
    iconName: 'CloudSnow',
    accentColor: '#93c5fd',
    bgGradientDay: 'from-slate-900 via-sky-950 to-slate-950',
    bgGradientNight: 'from-black via-slate-950 to-black',
  },
  67: {
    condition: 'Heavy Freezing Rain',
    description: 'Hazardous freezing rain causing hazardous black ice',
    themeTypeDay: 'heavy-rain',
    themeTypeNight: 'heavy-rain',
    iconName: 'CloudSnow',
    accentColor: '#bfdbfe',
    bgGradientDay: 'from-indigo-950 via-slate-950 to-black',
    bgGradientNight: 'from-black via-blue-950 to-black',
  },
  71: {
    condition: 'Slight Snow Fall',
    description: 'Light dancing snowflakes dusting the landscape',
    themeTypeDay: 'snow',
    themeTypeNight: 'snow',
    iconName: 'Snowflake',
    accentColor: '#e0f2fe',
    bgGradientDay: 'from-slate-800/80 via-blue-950/40 to-slate-950',
    bgGradientNight: 'from-slate-950 via-slate-900 to-black',
  },
  73: {
    condition: 'Moderate Snow Fall',
    description: 'Steady accumulation of crisp fluffy white snow',
    themeTypeDay: 'snow',
    themeTypeNight: 'snow',
    iconName: 'Snowflake',
    accentColor: '#f0f9ff',
    bgGradientDay: 'from-slate-700 via-indigo-950 to-slate-950',
    bgGradientNight: 'from-slate-950 via-indigo-950/50 to-black',
  },
  75: {
    condition: 'Heavy Snow Fall',
    description: 'Intense winter blizzard with thick snowfall accumulation',
    themeTypeDay: 'heavy-snow',
    themeTypeNight: 'heavy-snow',
    iconName: 'Snowflake',
    accentColor: '#ffffff',
    bgGradientDay: 'from-slate-800 via-slate-950 to-black',
    bgGradientNight: 'from-black via-slate-900 to-black',
  },
  77: {
    condition: 'Snow Grains',
    description: 'Tiny opaque ice grains bouncing quietly on surfaces',
    themeTypeDay: 'snow',
    themeTypeNight: 'snow',
    iconName: 'Snowflake',
    accentColor: '#bae6fd',
    bgGradientDay: 'from-slate-800 via-slate-900 to-slate-950',
    bgGradientNight: 'from-slate-950 via-slate-900 to-black',
  },
  80: {
    condition: 'Slight Rain Showers',
    description: 'Intermittent passing showers alternating with sun breaks',
    themeTypeDay: 'rain',
    themeTypeNight: 'rain',
    iconName: 'CloudSunRain',
    accentColor: '#38bdf8',
    bgGradientDay: 'from-blue-800/70 via-sky-950 to-slate-950',
    bgGradientNight: 'from-slate-950 via-blue-950 to-black',
  },
  81: {
    condition: 'Moderate Rain Showers',
    description: 'Brisk convective showers passing overhead',
    themeTypeDay: 'rain',
    themeTypeNight: 'rain',
    iconName: 'CloudRain',
    accentColor: '#0284c7',
    bgGradientDay: 'from-blue-900 via-slate-950 to-black',
    bgGradientNight: 'from-black via-blue-950 to-black',
  },
  82: {
    condition: 'Violent Rain Showers',
    description: 'Sudden intense cloudburst with torrential downpour',
    themeTypeDay: 'heavy-rain',
    themeTypeNight: 'heavy-rain',
    iconName: 'CloudRain',
    accentColor: '#1e40af',
    bgGradientDay: 'from-indigo-950 via-slate-950 to-black',
    bgGradientNight: 'from-black via-slate-950 to-black',
  },
  85: {
    condition: 'Slight Snow Showers',
    description: 'Passing flurry squalls dusting roofs and pathways',
    themeTypeDay: 'snow',
    themeTypeNight: 'snow',
    iconName: 'Snowflake',
    accentColor: '#e0f2fe',
    bgGradientDay: 'from-slate-800 via-indigo-950 to-slate-950',
    bgGradientNight: 'from-black via-slate-950 to-black',
  },
  86: {
    condition: 'Heavy Snow Showers',
    description: 'Brisk blinding snow squalls with swift accumulation',
    themeTypeDay: 'heavy-snow',
    themeTypeNight: 'heavy-snow',
    iconName: 'Snowflake',
    accentColor: '#ffffff',
    bgGradientDay: 'from-slate-900 via-slate-950 to-black',
    bgGradientNight: 'from-black via-indigo-950 to-black',
  },
  95: {
    condition: 'Thunderstorm',
    description: 'Electric storm with atmospheric thunder and lightning flashes',
    themeTypeDay: 'thunderstorm',
    themeTypeNight: 'thunderstorm',
    iconName: 'CloudLightning',
    accentColor: '#f59e0b',
    bgGradientDay: 'from-purple-950 via-slate-950 to-black',
    bgGradientNight: 'from-purple-950/80 via-black to-black',
  },
  96: {
    condition: 'Thunderstorm with Slight Hail',
    description: 'Severe electrical thunderstorm producing small hail pelts',
    themeTypeDay: 'thunderstorm',
    themeTypeNight: 'thunderstorm',
    iconName: 'CloudLightning',
    accentColor: '#eab308',
    bgGradientDay: 'from-amber-950/60 via-purple-950 to-slate-950',
    bgGradientNight: 'from-black via-purple-950 to-black',
  },
  99: {
    condition: 'Thunderstorm with Heavy Hail',
    description: 'High-energy supercell with violent hail and thunder',
    themeTypeDay: 'thunderstorm',
    themeTypeNight: 'thunderstorm',
    iconName: 'CloudLightning',
    accentColor: '#ef4444',
    bgGradientDay: 'from-rose-950/70 via-slate-950 to-black',
    bgGradientNight: 'from-black via-rose-950/40 to-black',
  },
};

export function getWmoInfo(weatherCode: number, isDay = true): WMOInfo {
  const match = WMO_CODE_MAP[weatherCode] || WMO_CODE_MAP[0];
  return match;
}

export function getThemeType(weatherCode: number, isDay = true): WeatherThemeType {
  const info = getWmoInfo(weatherCode, isDay);
  return isDay ? info.themeTypeDay : info.themeTypeNight;
}
